module.exports={
    google:{
        CLIENT_ID:'ID',
        CLIENT_SECRET:'SECRET'
    },
    fb:{
        CLIENT_ID:'ID',
        CLIENT_SECRET:'SECRET'
    },
    git:{
        CLIENT_ID:'ID',
        CLIENT_SECRET:'SECRET'
    }
}
